// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Ska7d4KvArrrRdOHQt9IFHJKSVL_lAs',
    appId: '1:113978093226:android:797dbce4c67edd7e03aad3',
    messagingSenderId: '113978093226',
    projectId: 'app1-71e16',
    databaseURL: 'https://app1-71e16-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app1-71e16.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7WBejgj4yAeBmRR5ptj6mljt8y6y6Juw',
    appId: '1:113978093226:web:3b18c4e6120020fa03aad3',
    messagingSenderId: '113978093226',
    projectId: 'app1-71e16',
    authDomain: 'app1-71e16.firebaseapp.com',
    databaseURL: 'https://app1-71e16-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app1-71e16.firebasestorage.app',
    measurementId: 'G-J376BS0LD6',
  );

}